/* eslint-disable react-refresh/only-export-components */
import { createContext, ReactNode, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'fr' | 'ar';

const languageNames: Record<Language, string> = {
  en: 'English',
  fr: 'Français',
  ar: 'العربية',
};

const translations: Record<Exclude<Language, 'en'>, Record<string, string>> = {
  fr: {
    'Discover · Play · Compete': 'Découvrir · Jouer · Se dépasser',
    NOW: 'MAINT.',
    Tournaments: 'Tournois',
    'Casual Meetups': 'Rencontres informelles',
    'Player Directory': 'Annuaire des joueurs',
    Map: 'Carte',
    'Event Map': 'Carte des événements',
    'Explore the event map': 'Explorer la carte des événements',
    'Chess event map': 'Carte des événements d’échecs',
    'Explore upcoming tournaments, casual meetups, and chess clubs across Morocco.': 'Découvrez les tournois, rencontres amicales et clubs d’échecs à venir au Maroc.',
    'Map markers show city centers, not exact venues.': 'Les marqueurs indiquent le centre des villes, pas les lieux exacts.',
    'Casual meetup': 'Rencontre amicale',
    'Chess club': 'Club d’échecs',
    Tournament: 'Tournoi',
    'No mapped events yet. Add city coordinates using the latest database migration.': 'Aucun événement cartographié. Ajoutez les coordonnées des villes avec la dernière migration.',
    'Browse meetups': 'Voir les rencontres',
    'Manage Clubs': 'Gérer les clubs',
    'Club Management': 'Gestion des clubs',
    'Create a club, review membership requests, and manage your roster.': 'Créez un club, examinez les demandes d’adhésion et gérez vos membres.',
    'Create Club': 'Créer un club',
    'Create a chess club': 'Créer un club d’échecs',
    'Club name': 'Nom du club',
    'Organizer access required to manage clubs.': 'L’accès organisateur est nécessaire pour gérer les clubs.',
    'No clubs managed yet': 'Aucun club à gérer',
    'Create your club to start building a local chess community.': 'Créez votre club pour développer une communauté échiquéenne locale.',
    'Pending requests': 'Demandes en attente',
    'Active members': 'Membres actifs',
    'Members and requests': 'Membres et demandes',
    'No members yet': 'Aucun membre pour le moment',
    'Membership requests will appear here.': 'Les demandes d’adhésion apparaîtront ici.',
    'Remove this member from the club?': 'Retirer ce membre du club ?',
    'Club member': 'Membre du club',
    'Membership request pending': 'Demande d’adhésion en attente',
    'Requesting...': 'Envoi de la demande...',
    'Request to join': 'Demander à rejoindre',
    'Request to join again': 'Demander à rejoindre à nouveau',
    'Club Teams': 'Équipes du club',
    'Create teams and assign active club members to their rosters.': 'Créez des équipes et affectez-y les membres actifs du club.',
    'Team name': 'Nom de l’équipe',
    'Create team': 'Créer une équipe',
    'No teams created for this club yet.': 'Aucune équipe créée pour ce club.',
    'No players assigned yet.': 'Aucun joueur affecté pour le moment.',
    'Choose active member': 'Choisir un membre actif',
    'Add': 'Ajouter',
    'Delete team': 'Supprimer l’équipe',
    'Delete this team?': 'Supprimer cette équipe ?',
    'Club teams and their rosters will appear here.': 'Les équipes du club et leurs effectifs apparaîtront ici.',
    'Join this club to view team rosters.': 'Rejoignez ce club pour voir les effectifs des équipes.',
    'Leave club': 'Quitter le club',
    'Leave this club? Your team assignments will also be removed.': 'Quitter ce club ? Vos affectations aux équipes seront également supprimées.',
    'Rounds and Standings': 'Rondes et classement',
    'Basic Swiss pairings; organizers confirm results.': 'Appariements suisses simplifiés ; les organisateurs valident les résultats.',
    'Automatic pairings are currently available for Swiss tournaments.': 'Les appariements automatiques sont actuellement disponibles pour les tournois suisses.',
    'Create next round': 'Créer la ronde suivante',
    'Creating round...': 'Création de la ronde...',
    'Enter all results in the current round before creating the next one.': 'Saisissez tous les résultats de la ronde en cours avant de créer la suivante.',
    'Swiss pairings cannot avoid a repeat opponent for this round.': 'Les appariements suisses ne peuvent éviter une nouvelle rencontre entre adversaires pour cette ronde.',
    'Could not create the tournament round.': 'Impossible de créer la ronde du tournoi.',
    'The incomplete round could not be removed:': 'La ronde incomplète n’a pas pu être supprimée :',
    'Could not load tournament pairings.': 'Impossible de charger les appariements du tournoi.',
    'Loading tournament pairings...': 'Chargement des appariements...',
    Round: 'Ronde',
    Bye: 'Exempt',
    'Pairing result': 'Résultat de la partie',
    'Result pending': 'Résultat en attente',
    'White wins': 'Les blancs gagnent',
    Draw: 'Nulle',
    'Black wins': 'Les noirs gagnent',
    'Standings': 'Classement',
    'Standings appear after the first round is paired.': 'Le classement apparaîtra après les premiers appariements.',
    Rank: 'Rang',
    Points: 'Points',
    open: 'en cours',
    completed: 'terminée',
    white_win: 'victoire des blancs',
    black_win: 'victoire des noirs',
    'Tournament Check-in': 'Pointage du tournoi',
    'Scan a player QR code or enter its code manually.': 'Scannez le QR code d’un joueur ou saisissez son code.',
    'Paste scanned QR token': 'Collez le code QR scanné',
    'Check-in token': 'Code de pointage',
    'Checking in...': 'Pointage en cours...',
    'Check in': 'Pointer la présence',
    'Scan with camera': 'Scanner avec la caméra',
    'Stop camera': 'Arrêter la caméra',
    'Could not start the camera scanner.': 'Impossible de démarrer le scanner.',
    'Enter a valid check-in QR code.': 'Saisissez un QR code de pointage valide.',
    'The check-in response was invalid.': 'La réponse du pointage est invalide.',
    'checked in successfully.': 'a été enregistré.',
    'Confirmed participants': 'Participants confirmés',
    'Loading participants...': 'Chargement des participants...',
    'No confirmed participants yet.': 'Aucun participant confirmé pour le moment.',
    'Player': 'Joueur',
    'Checked in': 'Présence enregistrée',
    'Not checked in': 'Présence non enregistrée',
    'Your event check-in QR code': 'Votre QR code de pointage',
    'Tournament check-in QR code': 'QR code de pointage du tournoi',
    'Preparing your QR code...': 'Préparation de votre QR code...',
    'Show this code to the organizer at the event.': 'Présentez ce code à l’organisateur lors de l’événement.',
    Messages: 'Messages',
    Message: 'Envoyer un message',
    'Meetup chat': 'Discussion de la rencontre',
    'Meetup group chat': 'Discussion de groupe',
    'Private conversation': 'Conversation privée',
    'Your conversations': 'Vos conversations',
    'Back to messages': 'Retour aux messages',
    'Direct message': 'Message privé',
    'No messages yet': 'Aucun message pour le moment',
    'Send the first message to start the conversation.': 'Envoyez le premier message pour commencer la conversation.',
    'Write a message...': 'Écrire un message...',
    'Send message': 'Envoyer le message',
    Send: 'Envoyer',
    'Sending...': 'Envoi...',
    'No conversations yet': 'Aucune conversation',
    'Open the player directory and message someone to start chatting.': 'Ouvrez l’annuaire des joueurs et contactez quelqu’un pour commencer à discuter.',
    'Player not found.': 'Joueur introuvable.',
    'Meetup not found.': 'Rencontre introuvable.',
    'Join this meetup before opening its group chat.': 'Rejoignez cette rencontre avant d’ouvrir la discussion de groupe.',
    You: 'Vous',
    Clubs: 'Clubs',
    Cities: 'Villes',
    Dashboard: 'Tableau de bord',
    'Organizer Panel': 'Espace organisateur',
    'Organizer Dashboard': 'Tableau de bord organisateur',
    'Admin Panel': 'Espace administrateur',
    'Admin Dashboard': 'Tableau de bord administrateur',
    'Could not load admin data:': 'Impossible de charger les données administrateur :',
    'Could not update tournament:': 'Impossible de mettre à jour le tournoi :',
    'Sign Out': 'Déconnexion',
    'Sign In': 'Connexion',
    'Sign Up': 'Créer un compte',
    'Get Started': 'Commencer',
    Explore: 'Explorer',
    'Chess Clubs': 'Clubs d’échecs',
    'Become an Organizer': 'Devenir organisateur',
    Contact: 'Contact',
    'All rights reserved.': 'Tous droits réservés.',
    "Morocco's #1 Chess Tournament Platform": 'La plateforme n° 1 des tournois d’échecs au Maroc',
    'Find your next chess': 'Trouvez votre prochain tournoi',
    ' tournament in Morocco': ' d’échecs au Maroc',
    'Discover tournaments happening across the kingdom — from Casablanca to Tangier. Browse by city, format, or date, and register in seconds.':
      'Découvrez les tournois partout au Maroc, de Casablanca à Tanger. Recherchez par ville, format ou date et inscrivez-vous en quelques secondes.',
    'Browse Tournaments': 'Voir les tournois',
    'Find a casual game': 'Trouver une partie amicale',
    'Browse Players': 'Parcourir les joueurs',
    'Find chess players in your city and discover their chess accounts.': 'Trouvez des joueurs dans votre ville et découvrez leurs comptes d’échecs.',
    'Nearby matching uses approximate city-center locations. Your device location stays in this browser and is not saved.': 'La recherche à proximité utilise les centres approximatifs des villes. Votre position reste dans ce navigateur et n’est pas enregistrée.',
    'Your device location is used only in this browser and is not saved.': 'La position de votre appareil est utilisée uniquement dans ce navigateur et n’est pas enregistrée.',
    'Find players near me': 'Trouver des joueurs près de moi',
    'Find events near me': 'Trouver des événements près de moi',
    'Refresh nearby players': 'Actualiser les joueurs à proximité',
    'Refresh nearby events': 'Actualiser les événements à proximité',
    'Finding your location...': 'Recherche de votre position...',
    'Within': 'Dans un rayon de',
    'Search radius': 'Rayon de recherche',
    'km': 'km',
    'km away': 'km de vous',
    'Nearby players are sorted by distance to their city center; exact player locations are not shared.': 'Les joueurs sont triés selon la distance au centre de leur ville ; leur position exacte n’est pas partagée.',
    'Open a player card and choose Message to start a private chat.': 'Ouvrez la fiche d’un joueur et choisissez Envoyer un message pour démarrer une conversation privée.',
    'Find a game now': 'Trouver une partie maintenant',
    'Show nearby players that you are available for a chess game. This expires automatically in two hours.': 'Indiquez aux joueurs proches que vous êtes disponible pour jouer. Cette disponibilité expire automatiquement après deux heures.',
    'Preferred time control': 'Cadence préférée',
    'I’m available': 'Je suis disponible',
    'Stop looking': 'Ne plus chercher',
    'Could not update availability. Please try again.': 'Impossible de mettre à jour votre disponibilité. Veuillez réessayer.',
    'You are open to play': 'Vous êtes disponible pour jouer',
    'Show players open to play': 'Afficher les joueurs disponibles',
    'Open to play': 'Disponible pour jouer',
    'Showing city-center events within': 'Événements selon le centre de leur ville dans un rayon de',
    'nearby locations': 'lieux à proximité',
    'No events or clubs were found within this radius.': 'Aucun événement ni club trouvé dans ce rayon.',
    'Location permission was denied. Allow location access in your browser settings to find nearby players.': 'Autorisation de localisation refusée. Autorisez l’accès à la position dans les paramètres du navigateur pour trouver les joueurs proches.',
    'Location permission was denied. Allow location access in your browser settings to find nearby events.': 'Autorisation de localisation refusée. Autorisez l’accès à la position dans les paramètres du navigateur pour trouver les événements proches.',
    'Your location could not be found in time. Please try again.': 'La recherche de votre position a expiré. Veuillez réessayer.',
    'Location is unavailable in this browser or device.': 'La localisation est indisponible sur ce navigateur ou cet appareil.',
    'Could not get your location. Please try again.': 'Impossible d’obtenir votre position. Veuillez réessayer.',
    'Search players...': 'Rechercher des joueurs...',
    'No players found': 'Aucun joueur trouvé',
    'No chess accounts linked yet.': 'Aucun compte d’échecs associé pour le moment.',
    'Join the Community': 'Rejoindre la communauté',
    'Featured Tournaments': 'Tournois à la une',
    "Hand-picked events you don't want to miss": 'Une sélection d’événements à ne pas manquer',
    'View all': 'Tout voir',
    'Happening Soon': 'Prochainement',
    'Next tournaments across Morocco': 'Prochains tournois au Maroc',
    'See all upcoming': 'Voir tous les prochains',
    'Everything Chess in Morocco': 'Les échecs partout au Maroc',
    'One platform for the entire Moroccan chess ecosystem': 'Une plateforme pour tout l’écosystème des échecs marocains',
    'Discover Tournaments': 'Découvrir les tournois',
    'Search and filter tournaments by city, format, date, or club. Find exactly what you are looking for in seconds.':
      'Recherchez et filtrez les tournois par ville, format, date ou club. Trouvez ce que vous cherchez en quelques secondes.',
    'Easy Registration': 'Inscription facile',
    'Register for tournaments in just a few clicks. Track your registrations and never miss a tournament again.':
      'Inscrivez-vous aux tournois en quelques clics. Suivez vos inscriptions et ne manquez plus aucun tournoi.',
    'Are you organizing a chess tournament?': 'Vous organisez un tournoi d’échecs ?',
    'Publish your tournament on Qehwa Chess and reach thousands of players across the country. Manage registrations and grow your event.':
      'Publiez votre tournoi sur Qehwa Chess et touchez des milliers de joueurs. Gérez les inscriptions et développez votre événement.',
    'Tournaments across Morocco': 'Tournois au Maroc',
    'Tournaments organized by this club': 'Tournois organisés par ce club',
    'No upcoming tournaments': 'Aucun tournoi à venir',
    "This club hasn't published any tournaments yet.": 'Ce club n’a pas encore publié de tournoi.',
    'Upcoming Tournaments': 'Tournois à venir',
    'No tournaments found': 'Aucun tournoi trouvé',
    'No clubs yet': 'Aucun club pour le moment',
    'No cities available': 'Aucune ville disponible',
    'No tournaments in this city': 'Aucun tournoi dans cette ville',
    'Check back later or explore other cities.': 'Revenez plus tard ou explorez d’autres villes.',
    'Back to cities': 'Retour aux villes',
    'Back to clubs': 'Retour aux clubs',
    'Back to tournaments': 'Retour aux tournois',
    'Search by name, venue, or description...': 'Rechercher par nom, lieu ou description...',
    Filters: 'Filtres',
    City: 'Ville',
    'All cities': 'Toutes les villes',
    'All formats': 'Tous les formats',
    'Clear all filters': 'Effacer tous les filtres',
    'No tournaments yet': 'Aucun tournoi pour le moment',
    'Create your first tournament to start accepting registrations.': 'Créez votre premier tournoi pour commencer à recevoir des inscriptions.',
    'New tournaments require admin approval before players can see or join them.': 'Les nouveaux tournois doivent être approuvés par un administrateur avant que les joueurs puissent les voir ou s’inscrire.',
    'Create Tournament': 'Créer un tournoi',
    'New Tournament': 'Nouveau tournoi',
    'Manage your tournaments and registrations': 'Gérez vos tournois et inscriptions',
    'My Dashboard': 'Mon tableau de bord',
    Upcoming: 'À venir',
    'Past Events': 'Événements passés',
    Active: 'Actives',
    'Browse tournaments and register to see them here.': 'Parcourez les tournois et inscrivez-vous pour les retrouver ici.',
    'Past Tournaments': 'Tournois passés',
    'Total Users': 'Utilisateurs',
    Organizers: 'Organisateurs',
    Players: 'Joueurs',
    Overview: 'Vue d’ensemble',
    Users: 'Utilisateurs',
    'Pending Review': 'En attente de révision',
    Published: 'Publiés',
    'Pending Approvals': 'Approbations en attente',
    'Recent Registrations': 'Inscriptions récentes',
    'No registrations yet.': 'Aucune inscription pour le moment.',
    Approve: 'Approuver',
    'No tournaments': 'Aucun tournoi',
    'No users': 'Aucun utilisateur',
    'Profile Settings': 'Paramètres du profil',
    'Update your personal information': 'Mettez à jour vos informations personnelles',
    'Profile updated successfully!': 'Profil mis à jour avec succès !',
    'Chess accounts': 'Comptes d’échecs',
    'These usernames are profile links only; ratings are not verified or synchronized.': 'Ces noms d’utilisateur sont de simples liens de profil ; les classements ne sont ni vérifiés ni synchronisés.',
    'Player username': 'Nom d’utilisateur',
    '3–24 letters, numbers, or underscores': '3 à 24 lettres, chiffres ou tirets bas',
    'Username must be 3–24 letters, numbers, or underscores.': 'Le nom d’utilisateur doit contenir de 3 à 24 lettres, chiffres ou tirets bas.',
    'Full name is required.': 'Le nom complet est obligatoire.',
    'City is required.': 'La ville est obligatoire.',
    'Link at least one chess account': 'Associez au moins un compte d’échecs',
    'Add a Chess.com username, Lichess username, or FIDE ID. Ratings are not verified during sign-up.': 'Ajoutez un nom d’utilisateur Chess.com ou Lichess, ou un identifiant FIDE. Les classements ne sont pas vérifiés lors de l’inscription.',
    'Enter at least one Chess.com, Lichess, or FIDE ID.': 'Saisissez au moins un identifiant Chess.com, Lichess ou FIDE.',
    'FIDE ID': 'Identifiant FIDE',
    'Profile photo': 'Photo de profil',
    'Choose photo': 'Choisir une photo',
    'Uploading...': 'Téléversement...',
    'Choose a JPEG, PNG, WebP, or GIF image no larger than 5 MB.': 'Choisissez une image JPEG, PNG, WebP ou GIF de 5 Mo maximum.',
    'Find a nearby player and arrange a casual game.': 'Trouvez un joueur près de chez vous et organisez une partie amicale.',
    'Post a meetup': 'Proposer une rencontre',
    Close: 'Fermer',
    'Create a casual game': 'Créer une partie amicale',
    'e.g. Casual blitz at the café': 'Ex. : blitz amical au café',
    'Date and time': 'Date et heure',
    'Address (optional)': 'Adresse (facultative)',
    'Café, park, or chess club': 'Café, parc ou club d’échecs',
    'Skill level': 'Niveau',
    'Casual / no clock': 'Amical / sans pendule',
    'Blitz (3+0)': 'Blitz (3+0)',
    'Blitz (5+3)': 'Blitz (5+3)',
    'Rapid (10+0)': 'Rapide (10+0)',
    'Rapid (15+10)': 'Rapide (15+10)',
    'Description (optional)': 'Description (facultative)',
    'Publishing...': 'Publication...',
    'Publish meetup': 'Publier la rencontre',
    'Search meetups...': 'Rechercher des rencontres...',
    'Filter by city': 'Filtrer par ville',
    'No upcoming meetups': 'Aucune rencontre à venir',
    'Be the first to post a casual chess game in your city.': 'Soyez le premier à proposer une partie amicale dans votre ville.',
    'Open map': 'Ouvrir la carte',
    'Your meetup': 'Votre rencontre',
    'Cancel attendance': 'Annuler ma participation',
    'Join meetup': 'Rejoindre la rencontre',
    'Sign in to join this meetup.': 'Connectez-vous pour rejoindre cette rencontre.',
    'Any level': 'Tous niveaux',
    Beginner: 'Débutant',
    Intermediate: 'Intermédiaire',
    Advanced: 'Avancé',
    'Full Name': 'Nom complet',
    'Email (read-only)': 'E-mail (lecture seule)',
    Phone: 'Téléphone',
    Bio: 'Biographie',
    'Select city': 'Choisir une ville',
    'Save Changes': 'Enregistrer les modifications',
    'Saving...': 'Enregistrement...',
    'Welcome back': 'Bon retour',
    'Sign in to your Qehwa Chess account': 'Connectez-vous à votre compte Qehwa Chess',
    'Account created. Check your email for a confirmation link before signing in.': 'Compte créé. Consultez votre e-mail et cliquez sur le lien de confirmation avant de vous connecter.',
    'Confirmation email sent. Check your inbox and spam folder.': 'E-mail de confirmation envoyé. Vérifiez votre boîte de réception et vos courriers indésirables.',
    'Sending confirmation email...': 'Envoi de l’e-mail de confirmation...',
    'Resend confirmation email': 'Renvoyer l’e-mail de confirmation',
    'Email not confirmed': 'Adresse e-mail non confirmée',
    Password: 'Mot de passe',
    "Don't have an account?": 'Vous n’avez pas de compte ?',
    'Already have an account?': 'Vous avez déjà un compte ?',
    'Create Account': 'Créer un compte',
    'Creating account...': 'Création du compte...',
    'Join Qehwa Chess': 'Rejoindre Qehwa Chess',
    'Create your account and start discovering tournaments': 'Créez votre compte et découvrez les tournois',
    'I want to...': 'Je souhaite...',
    Play: 'Jouer',
    Organize: 'Organiser',
    'Find & join tournaments': 'Trouver et rejoindre des tournois',
    'Publish tournaments': 'Publier des tournois',
    'Your name': 'Votre nom',
    'At least 6 characters': 'Au moins 6 caractères',
    'City (optional)': 'Ville (facultatif)',
    'Select your city': 'Choisissez votre ville',
    'Choose your language': 'Choisissez votre langue',
    'You can change this anytime from the menu.': 'Vous pourrez modifier ce choix à tout moment dans le menu.',
    Continue: 'Continuer',
    'Language / Langue': 'Langue',
    'The central platform for chess in Morocco. Discover tournaments across the kingdom, connect with clubs, and compete with the best players in the country.': 'La plateforme centrale des échecs au Maroc. Découvrez les tournois, rejoignez des clubs et affrontez les meilleurs joueurs du pays.',
    'Built for the Moroccan chess community': 'Au service de la communauté échiquéenne marocaine',
    'Discover chess tournaments happening across Morocco': 'Découvrez les tournois d’échecs organisés partout au Maroc',
    'Try adjusting your search or filters to find tournaments.': 'Modifiez votre recherche ou vos filtres pour trouver des tournois.',
    'Discover chess clubs across Morocco and their events': 'Découvrez les clubs d’échecs au Maroc et leurs événements',
    'Chess clubs will appear here once organizers register them.': 'Les clubs apparaîtront ici lorsque les organisateurs les auront inscrits.',
    'Explore chess tournaments by city across Morocco': 'Explorez les tournois d’échecs par ville au Maroc',
    event: 'événement',
    events: 'événements',
    'Explore tournaments': 'Explorer les tournois',
    tournament: 'tournoi',
    tournaments: 'tournois',
    club: 'club',
    clubs: 'clubs',
    'Tournaments in': 'Tournois à',
    in: 'dans',
    'City not found.': 'Ville introuvable.',
    'Chess club not found.': 'Club d’échecs introuvable.',
    'Today!': 'Aujourd’hui !',
    Today: 'Aujourd’hui',
    Tomorrow: 'Demain',
    days: 'jours',
    day: 'jour',
    Completed: 'Terminé',
    Full: 'Complet',
    spots: 'places',
    'No tournaments pending review.': 'Aucun tournoi en attente de validation.',
    by: 'par',
    'Admin access required. This area is restricted to platform administrators.': 'Accès administrateur requis. Cette zone est réservée aux administrateurs.',
    'Platform moderation and management': 'Modération et gestion de la plateforme',
    'You need an organizer account to access this page.': 'Un compte organisateur est nécessaire pour accéder à cette page.',
    'Are you sure you want to delete this tournament? This cannot be undone.': 'Voulez-vous vraiment supprimer ce tournoi ? Cette action est irréversible.',
    Total: 'Total',
    Pending: 'En attente',
    'Edit Tournament': 'Modifier le tournoi',
    Title: 'Titre',
    'Tournament name': 'Nom du tournoi',
    Description: 'Description',
    'Describe the tournament...': 'Décrivez le tournoi...',
    'Club (optional)': 'Club (facultatif)',
    'No club': 'Aucun club',
    'Start Date': 'Date de début',
    'End Date': 'Date de fin',
    Venue: 'Lieu',
    'Venue name': 'Nom du lieu',
    Address: 'Adresse',
    'Full address': 'Adresse complète',
    'Time Control': 'Cadence',
    'Max Participants': 'Nombre maximal de participants',
    'Entry Fee (MAD)': 'Frais d’inscription (MAD)',
    Status: 'Statut',
    'Contact Email': 'E-mail de contact',
    'Contact Phone': 'Téléphone de contact',
    'Image URL (optional)': 'URL de l’image (facultatif)',
    Cancel: 'Annuler',
    Update: 'Mettre à jour',
    Create: 'Créer',
    'You are already registered for this tournament.': 'Vous êtes déjà inscrit à ce tournoi.',
    "You've been added to the waitlist!": 'Vous avez été ajouté à la liste d’attente !',
    "You're registered! See you at the tournament.": 'Votre inscription est confirmée ! À bientôt au tournoi.',
    'Your registration has been cancelled.': 'Votre inscription a été annulée.',
    Dates: 'Dates',
    TBD: 'À confirmer',
    Format: 'Format',
    Capacity: 'Capacité',
    players: 'joueurs',
    'No deadline': 'Aucune date limite',
    In: 'Dans',
    'About this tournament': 'À propos de ce tournoi',
    'Tournament Details': 'Détails du tournoi',
    'Prize Fund': 'Dotation',
    'Organized by': 'Organisé par',
    'Contact Organizer': 'Contacter l’organisateur',
    'Available spots': 'Places disponibles',
    left: 'restantes',
    registered: 'inscrits',
    'Tournament Ended': 'Tournoi terminé',
    "You're registered!": 'Vous êtes inscrit !',
    'Cancelling...': 'Annulation...',
    'Cancel Registration': 'Annuler l’inscription',
    'Registration Closed': 'Inscriptions clôturées',
    'Joining waitlist...': 'Ajout à la liste d’attente...',
    'Join Waitlist': 'Rejoindre la liste d’attente',
    Registering: 'Inscription...',
    'Registering...': 'Inscription...',
    'Register Now': 'S’inscrire maintenant',
    'Sign In to Register': 'Connectez-vous pour vous inscrire',
    'Need an account?': 'Besoin d’un compte ?',
    'Quick Info': 'Informations rapides',
    'Signing in...': 'Connexion...',
    Email: 'E-mail',
    'Tell the community about yourself...': 'Parlez de vous à la communauté...',
    'Total Registrations': 'Inscriptions totales',
    'Only player accounts can register for tournaments.': 'Seuls les comptes joueurs peuvent s’inscrire aux tournois.',
    'Tournament in Morocco': 'Tournoi au Maroc',
    'Starts': 'Début',
    'max': 'max.',
    'e.g. 15,000 MAD total': 'ex. 15 000 MAD au total',
    'organizer@email.com': 'organisateur@email.com',
    'Swiss System': 'Système suisse',
    'Round Robin': 'Toutes rondes',
    Knockout: 'Élimination directe',
    Blitz: 'Blitz',
    Rapid: 'Rapide',
    Classical: 'Classique',
    Simultaneous: 'Simultanée',
    Free: 'Gratuit',
    Draft: 'Brouillon',
    draft: 'brouillon',
    Cancelled: 'Annulé',
    player: 'joueur',
    organizer: 'organisateur',
    admin: 'administrateur',
    'Explore chess clubs across Morocco, see their upcoming events, and connect with your local chess community.': 'Découvrez les clubs d’échecs au Maroc, leurs événements à venir et votre communauté locale.',
    'Casablanca, Morocco': 'Casablanca, Maroc',
    confirmed: 'confirmée',
    waitlisted: 'en liste d’attente',
    cancelled: 'annulée',
    'Sign-ups are temporarily rate-limited by Supabase. Please wait a while before trying again.': 'Les inscriptions sont temporairement limitées par Supabase. Veuillez patienter avant de réessayer.',
    'Invalid login credentials': 'Identifiants de connexion invalides',
  },
  ar: {
    'Discover · Play · Compete': 'اكتشف · العب · نافس',
    NOW: 'الآن',
    Tournaments: 'البطولات',
    'Casual Meetups': 'لقاءات ودية',
    'Player Directory': 'دليل اللاعبين',
    Map: 'الخريطة',
    'Event Map': 'خريطة الفعاليات',
    'Explore the event map': 'استكشف خريطة الفعاليات',
    'Chess event map': 'خريطة فعاليات الشطرنج',
    'Explore upcoming tournaments, casual meetups, and chess clubs across Morocco.': 'استكشف البطولات القادمة واللقاءات الودية وأندية الشطرنج في المغرب.',
    'Map markers show city centers, not exact venues.': 'تشير العلامات إلى مراكز المدن وليس إلى الأماكن الدقيقة.',
    'Casual meetup': 'لقاء ودي',
    'Chess club': 'نادي شطرنج',
    Tournament: 'بطولة',
    'No mapped events yet. Add city coordinates using the latest database migration.': 'لا توجد فعاليات على الخريطة. أضف إحداثيات المدن عبر آخر ترحيل لقاعدة البيانات.',
    'Browse meetups': 'تصفح اللقاءات',
    'Manage Clubs': 'إدارة الأندية',
    'Club Management': 'إدارة النادي',
    'Create a club, review membership requests, and manage your roster.': 'أنشئ نادياً وراجع طلبات العضوية وأدر قائمة الأعضاء.',
    'Create Club': 'أنشئ نادياً',
    'Create a chess club': 'أنشئ نادياً للشطرنج',
    'Club name': 'اسم النادي',
    'Organizer access required to manage clubs.': 'يلزم صلاحية المنظم لإدارة الأندية.',
    'No clubs managed yet': 'لا توجد أندية لإدارتها بعد',
    'Create your club to start building a local chess community.': 'أنشئ ناديك لبدء بناء مجتمع شطرنج محلي.',
    'Pending requests': 'الطلبات المعلقة',
    'Active members': 'الأعضاء النشطون',
    'Members and requests': 'الأعضاء والطلبات',
    'No members yet': 'لا يوجد أعضاء بعد',
    'Membership requests will appear here.': 'ستظهر طلبات العضوية هنا.',
    'Remove this member from the club?': 'هل تريد إزالة هذا العضو من النادي؟',
    'Club member': 'عضو النادي',
    'Membership request pending': 'طلب العضوية قيد الانتظار',
    'Requesting...': 'جارٍ إرسال الطلب...',
    'Request to join': 'طلب الانضمام',
    'Request to join again': 'اطلب الانضمام مجدداً',
    'Club Teams': 'فرق النادي',
    'Create teams and assign active club members to their rosters.': 'أنشئ فرقاً وعيّن أعضاء النادي النشطين إلى قوائمها.',
    'Team name': 'اسم الفريق',
    'Create team': 'أنشئ فريقاً',
    'No teams created for this club yet.': 'لم يتم إنشاء فرق لهذا النادي بعد.',
    'No players assigned yet.': 'لم يتم تعيين لاعبين بعد.',
    'Choose active member': 'اختر عضواً نشطاً',
    Add: 'إضافة',
    'Delete team': 'حذف الفريق',
    'Delete this team?': 'هل تريد حذف هذا الفريق؟',
    'Club teams and their rosters will appear here.': 'ستظهر فرق النادي وقوائم أعضائها هنا.',
    'Join this club to view team rosters.': 'انضم إلى النادي لرؤية قوائم أعضاء الفرق.',
    'Leave club': 'مغادرة النادي',
    'Leave this club? Your team assignments will also be removed.': 'هل تريد مغادرة النادي؟ ستتم إزالة عضويتك من الفرق أيضاً.',
    'Rounds and Standings': 'الجولات والترتيب',
    'Basic Swiss pairings; organizers confirm results.': 'نظام سويسري مبسط؛ يؤكد المنظمون النتائج.',
    'Automatic pairings are currently available for Swiss tournaments.': 'الاقتران التلقائي متاح حالياً للبطولات السويسرية.',
    'Create next round': 'إنشاء الجولة التالية',
    'Creating round...': 'جارٍ إنشاء الجولة...',
    'Enter all results in the current round before creating the next one.': 'أدخل جميع نتائج الجولة الحالية قبل إنشاء الجولة التالية.',
    'Swiss pairings cannot avoid a repeat opponent for this round.': 'تعذر تجنب تكرار مواجهة خصم في هذه الجولة السويسرية.',
    'Could not create the tournament round.': 'تعذر إنشاء جولة البطولة.',
    'The incomplete round could not be removed:': 'تعذر حذف الجولة غير المكتملة:',
    'Could not load tournament pairings.': 'تعذر تحميل اقترانات البطولة.',
    'Loading tournament pairings...': 'جارٍ تحميل اقترانات البطولة...',
    Round: 'جولة',
    Bye: 'إعفاء',
    'Pairing result': 'نتيجة المباراة',
    'Result pending': 'النتيجة معلقة',
    'White wins': 'فوز الأبيض',
    Draw: 'تعادل',
    'Black wins': 'فوز الأسود',
    Standings: 'الترتيب',
    'Standings appear after the first round is paired.': 'سيظهر الترتيب بعد إنشاء اقترانات الجولة الأولى.',
    Rank: 'المركز',
    Points: 'النقاط',
    open: 'مفتوحة',
    completed: 'مكتملة',
    white_win: 'فوز الأبيض',
    black_win: 'فوز الأسود',
    'Tournament Check-in': 'تسجيل الحضور للبطولة',
    'Scan a player QR code or enter its code manually.': 'امسح رمز QR للاعب أو أدخل الرمز يدوياً.',
    'Paste scanned QR token': 'أدخل رمز QR الممسوح',
    'Check-in token': 'رمز تسجيل الحضور',
    'Checking in...': 'جارٍ تسجيل الحضور...',
    'Check in': 'تسجيل الحضور',
    'Scan with camera': 'المسح بالكاميرا',
    'Stop camera': 'إيقاف الكاميرا',
    'Could not start the camera scanner.': 'تعذر تشغيل الماسح بالكاميرا.',
    'Enter a valid check-in QR code.': 'أدخل رمز QR صالحاً لتسجيل الحضور.',
    'The check-in response was invalid.': 'استجابة تسجيل الحضور غير صالحة.',
    'checked in successfully.': 'تم تسجيل حضوره بنجاح.',
    'Confirmed participants': 'المشاركون المؤكدون',
    'Loading participants...': 'جارٍ تحميل المشاركين...',
    'No confirmed participants yet.': 'لا يوجد مشاركون مؤكدون بعد.',
    Player: 'لاعب',
    'Checked in': 'تم تسجيل الحضور',
    'Not checked in': 'لم يتم تسجيل الحضور',
    'Your event check-in QR code': 'رمز QR الخاص بك لتسجيل الحضور',
    'Tournament check-in QR code': 'رمز QR لتسجيل حضور البطولة',
    'Preparing your QR code...': 'جارٍ إعداد رمز QR...',
    'Show this code to the organizer at the event.': 'اعرض هذا الرمز على المنظم في الفعالية.',
    Messages: 'الرسائل',
    Message: 'أرسل رسالة',
    'Meetup chat': 'محادثة اللقاء',
    'Meetup group chat': 'محادثة جماعية',
    'Private conversation': 'محادثة خاصة',
    'Your conversations': 'محادثاتك',
    'Back to messages': 'العودة إلى الرسائل',
    'Direct message': 'رسالة خاصة',
    'No messages yet': 'لا توجد رسائل بعد',
    'Send the first message to start the conversation.': 'أرسل الرسالة الأولى لبدء المحادثة.',
    'Write a message...': 'اكتب رسالة...',
    'Send message': 'أرسل الرسالة',
    Send: 'إرسال',
    'Sending...': 'جارٍ الإرسال...',
    'No conversations yet': 'لا توجد محادثات بعد',
    'Open the player directory and message someone to start chatting.': 'افتح دليل اللاعبين وأرسل رسالة إلى أحدهم لبدء الدردشة.',
    'Player not found.': 'لم يتم العثور على اللاعب.',
    'Meetup not found.': 'لم يتم العثور على اللقاء.',
    'Join this meetup before opening its group chat.': 'انضم إلى اللقاء قبل فتح المحادثة الجماعية.',
    You: 'أنت',
    Clubs: 'الأندية',
    Cities: 'المدن',
    Dashboard: 'لوحة التحكم',
    'Organizer Panel': 'لوحة المنظم',
    'Organizer Dashboard': 'لوحة تحكم المنظم',
    'Admin Panel': 'لوحة المدير',
    'Admin Dashboard': 'لوحة تحكم المدير',
    'Could not load admin data:': 'تعذر تحميل بيانات المدير:',
    'Could not update tournament:': 'تعذر تحديث البطولة:',
    'Profile Settings': 'إعدادات الملف الشخصي',
    'Chess accounts': 'حسابات الشطرنج',
    'These usernames are profile links only; ratings are not verified or synchronized.': 'هذه أسماء مستخدمين للروابط فقط؛ لا يتم التحقق من التصنيفات أو مزامنتها.',
    'Player username': 'اسم المستخدم',
    '3–24 letters, numbers, or underscores': 'من 3 إلى 24 حرفاً أو رقماً أو شرطة سفلية',
    'Username must be 3–24 letters, numbers, or underscores.': 'يجب أن يتكون اسم المستخدم من 3 إلى 24 حرفاً أو رقماً أو شرطة سفلية.',
    'Full name is required.': 'الاسم الكامل مطلوب.',
    'City is required.': 'المدينة مطلوبة.',
    'Link at least one chess account': 'اربط حساب شطرنج واحداً على الأقل',
    'Add a Chess.com username, Lichess username, or FIDE ID. Ratings are not verified during sign-up.': 'أضف اسم مستخدم Chess.com أو Lichess أو رقم FIDE. لا يتم التحقق من التصنيف أثناء التسجيل.',
    'Enter at least one Chess.com, Lichess, or FIDE ID.': 'أدخل اسم مستخدم Chess.com أو Lichess أو رقم FIDE واحداً على الأقل.',
    'FIDE ID': 'رقم الاتحاد الدولي للشطرنج',
    'Profile photo': 'الصورة الشخصية',
    'Choose photo': 'اختر صورة',
    'Uploading...': 'جارٍ رفع الصورة...',
    'Choose a JPEG, PNG, WebP, or GIF image no larger than 5 MB.': 'اختر صورة JPEG أو PNG أو WebP أو GIF بحجم لا يتجاوز 5 ميغابايت.',
    'Find a nearby player and arrange a casual game.': 'اعثر على لاعب قريب ورتب مباراة ودية.',
    'Post a meetup': 'انشر لقاءً',
    Close: 'إغلاق',
    'Create a casual game': 'أنشئ مباراة ودية',
    'e.g. Casual blitz at the café': 'مثال: شطرنج خاطف ودي في المقهى',
    'Date and time': 'التاريخ والوقت',
    'Address (optional)': 'العنوان (اختياري)',
    'Café, park, or chess club': 'مقهى أو حديقة أو نادٍ للشطرنج',
    'Skill level': 'مستوى المهارة',
    'Casual / no clock': 'ودي / دون ساعة',
    'Blitz (3+0)': 'خاطف (3+0)',
    'Blitz (5+3)': 'خاطف (5+3)',
    'Rapid (10+0)': 'سريع (10+0)',
    'Rapid (15+10)': 'سريع (15+10)',
    'Description (optional)': 'الوصف (اختياري)',
    'Publishing...': 'جارٍ النشر...',
    'Publish meetup': 'انشر اللقاء',
    'Search meetups...': 'ابحث عن لقاءات...',
    'Filter by city': 'تصفية حسب المدينة',
    'No upcoming meetups': 'لا توجد لقاءات قادمة',
    'Be the first to post a casual chess game in your city.': 'كن أول من ينشر مباراة شطرنج ودية في مدينتك.',
    'Open map': 'افتح الخريطة',
    'Your meetup': 'لقاؤك',
    'Cancel attendance': 'إلغاء المشاركة',
    'Join meetup': 'انضم إلى اللقاء',
    'Sign in to join this meetup.': 'سجل الدخول للانضمام إلى هذا اللقاء.',
    'Any level': 'جميع المستويات',
    Beginner: 'مبتدئ',
    Intermediate: 'متوسط',
    Advanced: 'متقدم',
    'Sign Out': 'تسجيل الخروج',
    'Sign In': 'تسجيل الدخول',
    'Sign Up': 'إنشاء حساب',
    'Get Started': 'ابدأ الآن',
    Explore: 'استكشف',
    'Chess Clubs': 'نوادي الشطرنج',
    'Become an Organizer': 'كن منظماً',
    Contact: 'اتصل بنا',
    'All rights reserved.': 'جميع الحقوق محفوظة.',
    "Morocco's #1 Chess Tournament Platform": 'المنصة الأولى لبطولات الشطرنج في المغرب',
    'Find your next chess': 'اعثر على بطولة الشطرنج القادمة',
    ' tournament in Morocco': ' في المغرب',
    'Discover tournaments happening across the kingdom — from Casablanca to Tangier. Browse by city, format, or date, and register in seconds.':
      'اكتشف البطولات في جميع أنحاء المغرب، من الدار البيضاء إلى طنجة. ابحث حسب المدينة أو النظام أو التاريخ وسجل في ثوانٍ.',
    'Browse Tournaments': 'تصفح البطولات',
    'Find a casual game': 'ابحث عن مباراة ودية',
    'Browse Players': 'تصفح اللاعبين',
    'Find chess players in your city and discover their chess accounts.': 'اعثر على لاعبي الشطرنج في مدينتك واكتشف حساباتهم.',
    'Nearby matching uses approximate city-center locations. Your device location stays in this browser and is not saved.': 'يعتمد البحث القريب على مواقع تقريبية لمراكز المدن. تبقى إحداثيات جهازك في المتصفح ولا يتم حفظها.',
    'Your device location is used only in this browser and is not saved.': 'يتم استخدام موقع جهازك في هذا المتصفح فقط ولا يتم حفظه.',
    'Find players near me': 'العثور على لاعبين بالقرب مني',
    'Find events near me': 'العثور على فعاليات بالقرب مني',
    'Refresh nearby players': 'تحديث اللاعبين القريبين',
    'Refresh nearby events': 'تحديث الفعاليات القريبة',
    'Finding your location...': 'جارٍ تحديد موقعك...',
    Within: 'ضمن',
    'Search radius': 'نطاق البحث',
    km: 'كم',
    'km away': 'كم عنك',
    'Nearby players are sorted by distance to their city center; exact player locations are not shared.': 'يتم ترتيب اللاعبين حسب المسافة إلى مركز مدينتهم؛ ولا تتم مشاركة مواقعهم الدقيقة.',
    'Open a player card and choose Message to start a private chat.': 'افتح بطاقة اللاعب واختر إرسال رسالة لبدء محادثة خاصة.',
    'Find a game now': 'ابحث عن مباراة الآن',
    'Show nearby players that you are available for a chess game. This expires automatically in two hours.': 'أخبر اللاعبين القريبين أنك متاح للعب. ينتهي هذا تلقائياً بعد ساعتين.',
    'Preferred time control': 'نظام الوقت المفضل',
    'I’m available': 'أنا متاح',
    'Stop looking': 'إيقاف البحث',
    'Could not update availability. Please try again.': 'تعذر تحديث حالة التوفر. يرجى المحاولة مرة أخرى.',
    'You are open to play': 'أنت متاح للعب',
    'Show players open to play': 'عرض اللاعبين المتاحين للعب',
    'Open to play': 'متاح للعب',
    'Showing city-center events within': 'فعاليات مراكز المدن ضمن',
    'nearby locations': 'مواقع قريبة',
    'No events or clubs were found within this radius.': 'لم يتم العثور على فعاليات أو أندية ضمن هذا النطاق.',
    'Location permission was denied. Allow location access in your browser settings to find nearby players.': 'تم رفض إذن الموقع. اسمح بالوصول إلى الموقع من إعدادات المتصفح للعثور على لاعبين قريبين.',
    'Location permission was denied. Allow location access in your browser settings to find nearby events.': 'تم رفض إذن الموقع. اسمح بالوصول إلى الموقع من إعدادات المتصفح للعثور على فعاليات قريبة.',
    'Your location could not be found in time. Please try again.': 'انتهت مهلة تحديد موقعك. يرجى المحاولة مرة أخرى.',
    'Location is unavailable in this browser or device.': 'الموقع غير متاح في هذا المتصفح أو الجهاز.',
    'Could not get your location. Please try again.': 'تعذر تحديد موقعك. يرجى المحاولة مرة أخرى.',
    'Search players...': 'ابحث عن لاعبين...',
    'No players found': 'لم يتم العثور على لاعبين',
    'No chess accounts linked yet.': 'لا توجد حسابات شطرنج مرتبطة بعد.',
    'Join the Community': 'انضم إلى المجتمع',
    'Featured Tournaments': 'بطولات مميزة',
    "Hand-picked events you don't want to miss": 'فعاليات مختارة لا تفوتها',
    'View all': 'عرض الكل',
    'Happening Soon': 'قريباً',
    'Next tournaments across Morocco': 'البطولات القادمة في المغرب',
    'See all upcoming': 'عرض كل البطولات القادمة',
    'Everything Chess in Morocco': 'كل ما يتعلق بالشطرنج في المغرب',
    'One platform for the entire Moroccan chess ecosystem': 'منصة واحدة لمجتمع الشطرنج المغربي',
    'Discover Tournaments': 'اكتشف البطولات',
    'Search and filter tournaments by city, format, date, or club. Find exactly what you are looking for in seconds.':
      'ابحث عن البطولات وصنفها حسب المدينة أو النظام أو التاريخ أو النادي.',
    'Easy Registration': 'تسجيل سهل',
    'Register for tournaments in just a few clicks. Track your registrations and never miss a tournament again.':
      'سجل في البطولات ببضع نقرات، وتابع تسجيلاتك ولا تفوت أي بطولة.',
    'Are you organizing a chess tournament?': 'هل تنظم بطولة شطرنج؟',
    'Publish your tournament on Qehwa Chess and reach thousands of players across the country. Manage registrations and grow your event.':
      'انشر بطولتك على Qehwa Chess وتواصل مع آلاف اللاعبين. أدر التسجيلات وطوّر فعاليتك.',
    'Tournaments across Morocco': 'بطولات في المغرب',
    'Tournaments organized by this club': 'البطولات التي ينظمها هذا النادي',
    'No upcoming tournaments': 'لا توجد بطولات قادمة',
    "This club hasn't published any tournaments yet.": 'لم ينشر هذا النادي أي بطولات بعد.',
    'Upcoming Tournaments': 'البطولات القادمة',
    'No tournaments found': 'لم يتم العثور على بطولات',
    'No clubs yet': 'لا توجد أندية حالياً',
    'No cities available': 'لا توجد مدن متاحة',
    'No tournaments in this city': 'لا توجد بطولات في هذه المدينة',
    'Check back later or explore other cities.': 'عد لاحقاً أو استكشف مدناً أخرى.',
    'Back to cities': 'العودة إلى المدن',
    'Back to clubs': 'العودة إلى الأندية',
    'Back to tournaments': 'العودة إلى البطولات',
    'Search by name, venue, or description...': 'ابحث بالاسم أو المكان أو الوصف...',
    Filters: 'التصفية',
    City: 'المدينة',
    'All cities': 'كل المدن',
    'All formats': 'كل الأنظمة',
    'Clear all filters': 'مسح عوامل التصفية',
    'No tournaments yet': 'لا توجد بطولات بعد',
    'Create your first tournament to start accepting registrations.': 'أنشئ بطولتك الأولى لبدء استقبال التسجيلات.',
    'New tournaments require admin approval before players can see or join them.': 'تتطلب البطولات الجديدة موافقة المدير قبل أن يتمكن اللاعبون من رؤيتها أو الانضمام إليها.',
    'Create Tournament': 'إنشاء بطولة',
    'New Tournament': 'بطولة جديدة',
    'Manage your tournaments and registrations': 'أدر بطولاتك وتسجيلات المشاركين',
    'My Dashboard': 'لوحة التحكم الخاصة بي',
    'Total Registrations': 'إجمالي التسجيلات',
    Upcoming: 'قادمة',
    'Past Events': 'فعاليات سابقة',
    Active: 'نشطة',
    'Browse tournaments and register to see them here.': 'تصفح البطولات وسجل فيها لتظهر هنا.',
    'Past Tournaments': 'البطولات السابقة',
    'Total Users': 'إجمالي المستخدمين',
    Organizers: 'المنظمون',
    Players: 'اللاعبون',
    Overview: 'نظرة عامة',
    Users: 'المستخدمون',
    'Pending Review': 'بانتظار المراجعة',
    Published: 'منشورة',
    'Pending Approvals': 'طلبات بانتظار الموافقة',
    'Recent Registrations': 'التسجيلات الأخيرة',
    'No registrations yet.': 'لا توجد تسجيلات بعد.',
    Approve: 'موافقة',
    'No tournaments': 'لا توجد بطولات',
    'No users': 'لا يوجد مستخدمون',
    'Update your personal information': 'حدّث معلوماتك الشخصية',
    'Profile updated successfully!': 'تم تحديث الملف الشخصي بنجاح!',
    'Full Name': 'الاسم الكامل',
    'Email (read-only)': 'البريد الإلكتروني (للقراءة فقط)',
    Phone: 'الهاتف',
    Bio: 'نبذة',
    'Select city': 'اختر المدينة',
    'Save Changes': 'حفظ التغييرات',
    'Saving...': 'جارٍ الحفظ...',
    'Welcome back': 'مرحباً بعودتك',
    'Sign in to your Qehwa Chess account': 'سجل الدخول إلى حسابك في Qehwa Chess',
    'Account created. Check your email for a confirmation link before signing in.': 'تم إنشاء الحساب. تحقق من بريدك الإلكتروني واضغط رابط التأكيد قبل تسجيل الدخول.',
    'Confirmation email sent. Check your inbox and spam folder.': 'تم إرسال رسالة التأكيد. تحقق من صندوق الوارد والبريد العشوائي.',
    'Sending confirmation email...': 'جارٍ إرسال رسالة التأكيد...',
    'Resend confirmation email': 'إعادة إرسال رسالة التأكيد',
    'Email not confirmed': 'البريد الإلكتروني غير مؤكد',
    Password: 'كلمة المرور',
    "Don't have an account?": 'ليس لديك حساب؟',
    'Already have an account?': 'لديك حساب بالفعل؟',
    'Create Account': 'إنشاء حساب',
    'Creating account...': 'جارٍ إنشاء الحساب...',
    'Join Qehwa Chess': 'انضم إلى Qehwa Chess',
    'Create your account and start discovering tournaments': 'أنشئ حسابك وابدأ باكتشاف البطولات',
    'I want to...': 'أرغب في...',
    Play: 'اللعب',
    Organize: 'التنظيم',
    'Find & join tournaments': 'ابحث عن البطولات وانضم إليها',
    'Publish tournaments': 'انشر البطولات',
    'Your name': 'اسمك',
    'At least 6 characters': '6 أحرف على الأقل',
    'City (optional)': 'المدينة (اختياري)',
    'Select your city': 'اختر مدينتك',
    'Choose your language': 'اختر لغتك',
    'You can change this anytime from the menu.': 'يمكنك تغيير هذا الاختيار في أي وقت من القائمة.',
    Continue: 'متابعة',
    'Language / Langue': 'اللغة',
    'The central platform for chess in Morocco. Discover tournaments across the kingdom, connect with clubs, and compete with the best players in the country.': 'المنصة المركزية للشطرنج في المغرب. اكتشف البطولات وتواصل مع الأندية ونافس أفضل اللاعبين في البلاد.',
    'Built for the Moroccan chess community': 'صُمم لمجتمع الشطرنج المغربي',
    'Discover chess tournaments happening across Morocco': 'اكتشف بطولات الشطرنج في جميع أنحاء المغرب',
    'Try adjusting your search or filters to find tournaments.': 'حاول تعديل البحث أو عوامل التصفية للعثور على بطولات.',
    'Discover chess clubs across Morocco and their events': 'اكتشف نوادي الشطرنج وفعالياتها في المغرب',
    'Chess clubs will appear here once organizers register them.': 'ستظهر نوادي الشطرنج هنا بعد تسجيلها من قبل المنظمين.',
    'Explore chess tournaments by city across Morocco': 'استكشف بطولات الشطرنج حسب المدينة في المغرب',
    event: 'فعالية',
    events: 'فعاليات',
    'Explore tournaments': 'استكشف البطولات',
    tournament: 'بطولة',
    tournaments: 'بطولات',
    club: 'نادٍ',
    clubs: 'أندية',
    'Tournaments in': 'بطولات في',
    in: 'خلال',
    'City not found.': 'لم يتم العثور على المدينة.',
    'Chess club not found.': 'لم يتم العثور على نادي الشطرنج.',
    'Today!': 'اليوم!',
    Today: 'اليوم',
    Tomorrow: 'غداً',
    days: 'أيام',
    day: 'يوم',
    Completed: 'مكتمل',
    Full: 'مكتمل',
    spots: 'أماكن',
    'No tournaments pending review.': 'لا توجد بطولات بانتظار المراجعة.',
    by: 'بواسطة',
    'Admin access required. This area is restricted to platform administrators.': 'يلزم دخول المدير. هذه المنطقة مخصصة لمديري المنصة.',
    'Platform moderation and management': 'إدارة المنصة والإشراف عليها',
    'You need an organizer account to access this page.': 'تحتاج إلى حساب منظم للوصول إلى هذه الصفحة.',
    'Are you sure you want to delete this tournament? This cannot be undone.': 'هل أنت متأكد من حذف هذه البطولة؟ لا يمكن التراجع عن هذا الإجراء.',
    Total: 'الإجمالي',
    Pending: 'قيد الانتظار',
    'Edit Tournament': 'تعديل البطولة',
    Title: 'العنوان',
    'Tournament name': 'اسم البطولة',
    Description: 'الوصف',
    'Describe the tournament...': 'صف البطولة...',
    'Club (optional)': 'النادي (اختياري)',
    'No club': 'بدون نادٍ',
    'Start Date': 'تاريخ البداية',
    'End Date': 'تاريخ النهاية',
    Venue: 'المكان',
    'Venue name': 'اسم المكان',
    Address: 'العنوان',
    'Full address': 'العنوان الكامل',
    'Time Control': 'التحكم بالوقت',
    'Max Participants': 'الحد الأقصى للمشاركين',
    'Entry Fee (MAD)': 'رسوم الاشتراك (درهم)',
    Status: 'الحالة',
    'Contact Email': 'البريد الإلكتروني للتواصل',
    'Contact Phone': 'هاتف التواصل',
    'Image URL (optional)': 'رابط الصورة (اختياري)',
    Cancel: 'إلغاء',
    Update: 'تحديث',
    Create: 'إنشاء',
    'You are already registered for this tournament.': 'أنت مسجل بالفعل في هذه البطولة.',
    "You've been added to the waitlist!": 'تمت إضافتك إلى قائمة الانتظار!',
    "You're registered! See you at the tournament.": 'تم تسجيلك! نراك في البطولة.',
    'Your registration has been cancelled.': 'تم إلغاء تسجيلك.',
    Dates: 'التواريخ',
    TBD: 'يحدد لاحقاً',
    Capacity: 'السعة',
    players: 'لاعبين',
    'No deadline': 'لا يوجد موعد نهائي',
    In: 'خلال',
    'About this tournament': 'عن هذه البطولة',
    'Tournament Details': 'تفاصيل البطولة',
    'Prize Fund': 'قيمة الجوائز',
    'Organized by': 'ينظمها',
    'Contact Organizer': 'التواصل مع المنظم',
    'Available spots': 'الأماكن المتاحة',
    left: 'متبقية',
    registered: 'مسجل',
    'Tournament Ended': 'انتهت البطولة',
    "You're registered!": 'أنت مسجل!',
    'Cancelling...': 'جارٍ الإلغاء...',
    'Cancel Registration': 'إلغاء التسجيل',
    'Registration Closed': 'أُغلق التسجيل',
    'Joining waitlist...': 'جارٍ الانضمام لقائمة الانتظار...',
    'Join Waitlist': 'انضم لقائمة الانتظار',
    'Registering...': 'جارٍ التسجيل...',
    'Register Now': 'سجل الآن',
    'Sign In to Register': 'سجل الدخول للتسجيل',
    'Need an account?': 'تحتاج إلى حساب؟',
    'Quick Info': 'معلومات سريعة',
    'Signing in...': 'جارٍ تسجيل الدخول...',
    Email: 'البريد الإلكتروني',
    'Tell the community about yourself...': 'أخبر المجتمع عن نفسك...',
    'Only player accounts can register for tournaments.': 'يمكن لحسابات اللاعبين فقط التسجيل في البطولات.',
    Starts: 'البداية',
    max: 'الحد الأقصى',
    'e.g. 15,000 MAD total': 'مثال: 15,000 درهم إجمالي',
    'Swiss System': 'النظام السويسري',
    'Round Robin': 'دوري',
    Knockout: 'إقصائي',
    Blitz: 'خاطف',
    Rapid: 'سريع',
    Classical: 'كلاسيكي',
    Simultaneous: 'مباريات متزامنة',
    Free: 'مجاناً',
    Draft: 'مسودة',
    draft: 'مسودة',
    Cancelled: 'ملغاة',
    player: 'لاعب',
    organizer: 'منظم',
    admin: 'مدير',
    'Explore chess clubs across Morocco, see their upcoming events, and connect with your local chess community.': 'استكشف نوادي الشطرنج في المغرب وفعالياتها القادمة وتواصل مع مجتمعك المحلي.',
    'Casablanca, Morocco': 'الدار البيضاء، المغرب',
    confirmed: 'مؤكد',
    waitlisted: 'في قائمة الانتظار',
    cancelled: 'ملغاة',
    'Sign-ups are temporarily rate-limited by Supabase. Please wait a while before trying again.': 'التسجيلات محدودة مؤقتاً من قبل Supabase. يرجى الانتظار قبل إعادة المحاولة.',
    'Invalid login credentials': 'بيانات تسجيل الدخول غير صحيحة',
  },
};

interface LanguageContextValue {
  language: Language;
  hasChosenLanguage: boolean;
  chooseLanguage: (language: Language) => void;
  t: (text: string) => string;
  languageNames: Record<Language, string>;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('qehwa-language');
    return saved === 'en' || saved === 'fr' || saved === 'ar' ? saved : 'en';
  });
  const [hasChosenLanguage, setHasChosenLanguage] = useState(
    () => localStorage.getItem('qehwa-language') !== null
  );

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  function chooseLanguage(nextLanguage: Language) {
    localStorage.setItem('qehwa-language', nextLanguage);
    setLanguage(nextLanguage);
    setHasChosenLanguage(true);
  }

  function t(text: string) {
    return language === 'en' ? text : translations[language][text] ?? text;
  }

  return (
    <LanguageContext.Provider value={{ language, hasChosenLanguage, chooseLanguage, t, languageNames }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
